import 'category_hierarchy.dart';

/// Configuración default de categorías jerárquicas.
/// Incluye estructura completa de deportes con subcategorías específicas.
const List<CategoryHierarchy> defaultCategoriesHierarchy = [
  CategoryHierarchy(
    id: 'naturaleza',
    name: 'Naturaleza',
    emoji: '🌿',
    description: 'Paisajes naturales, flora y fauna',
    priority: 10,
    discoveryQueries: [
      'nature',
      'landscape',
      'forest',
      'mountain',
      'nature wallpaper',
      'landscape wallpaper',
      'natural scenery',
    ],
  ),
  CategoryHierarchy(
    id: 'paisajes-nocturnos',
    name: 'Paisajes nocturnos',
    emoji: '🌃',
    priority: 11,
    discoveryQueries: ['night landscape', 'night sky', 'starry night', 'night scenery'],
  ),
  CategoryHierarchy(
    id: 'espacio',
    name: 'Espacio',
    emoji: '🌌',
    description: 'Astronomía, planetas, galaxias, universo',
    priority: 12,
    discoveryQueries: [
      'space',
      'galaxy',
      'astronaut',
      'planet',
      'cosmic',
      'space wallpaper',
      'universe',
    ],
  ),
  CategoryHierarchy(
    id: 'abstracto',
    name: 'Abstracto',
    emoji: '🎨',
    priority: 13,
    discoveryQueries: ['abstract', 'abstract art', 'modern art', 'geometric'],
  ),
  CategoryHierarchy(
    id: 'minimalista',
    name: 'Minimalista',
    emoji: '⬛',
    priority: 14,
    discoveryQueries: ['minimal', 'minimalist', 'simple', 'clean design'],
  ),
  CategoryHierarchy(
    id: 'arquitectura',
    name: 'Arquitectura',
    emoji: '🏙️',
    priority: 15,
    discoveryQueries: ['architecture', 'building', 'city', 'urban', 'skyscraper'],
  ),
  CategoryHierarchy(
    id: 'animales',
    name: 'Animales',
    emoji: '🐾',
    priority: 16,
    discoveryQueries: ['animals', 'wildlife', 'dog', 'cat', 'bird', 'nature'],
  ),
  CategoryHierarchy(
    id: 'oscuro',
    name: 'Oscuro',
    emoji: '🌑',
    priority: 17,
    discoveryQueries: ['dark', 'black', 'dark background', 'dark wallpaper'],
  ),
  CategoryHierarchy(
    id: 'arte',
    name: 'Arte',
    emoji: '🖼️',
    priority: 18,
    discoveryQueries: ['art', 'artwork', 'painting', 'drawing', 'illustration'],
  ),
  CategoryHierarchy(
    id: 'autos-motos',
    name: 'Autos y motos',
    emoji: '🏎️',
    description: 'Automóviles, motocicletas, vehículos',
    priority: 20,
    discoveryQueries: [
      'car',
      'motorcycle',
      'auto',
      'vehicle',
      'sports car',
      'classic car',
      'car wallpaper',
    ],
  ),
  CategoryHierarchy(
    id: 'deportes',
    name: 'Deportes',
    emoji: '⚽',
    description: 'Deportes y competiciones atléticas',
    priority: 25,
    subcategories: [
      CategoryHierarchy(
        id: 'futbol',
        name: 'Fútbol',
        emoji: '⚽',
        priority: 1,
        discoveryQueries: [
          'football',
          'soccer',
          'soccer wallpaper',
          'football wallpaper',
        ],
        subcategories: [
          CategoryHierarchy(
            id: 'futbol-jugadores',
            name: 'Jugadores',
            emoji: '👤',
            discoveryQueries: [
              'Messi',
              'Ronaldo',
              'Mbappé',
              'Haaland',
              'Neymar',
              'Lewandowski',
              'Benzema',
              'player football',
            ],
          ),
          CategoryHierarchy(
            id: 'futbol-equipos',
            name: 'Equipos',
            emoji: '🏆',
            discoveryQueries: [
              'Real Madrid',
              'Barcelona',
              'Manchester City',
              'Liverpool',
              'Bayern Munich',
              'PSG',
              'Juventus',
              'Chelsea',
              'Arsenal',
              'AC Milan',
            ],
          ),
          CategoryHierarchy(
            id: 'futbol-competiciones',
            name: 'Competiciones',
            emoji: '🥇',
            discoveryQueries: [
              'Champions League',
              'La Liga',
              'Premier League',
              'Serie A',
              'Bundesliga',
              'Ligue 1',
              'Copa del Mundo',
              'Eurocopa',
            ],
          ),
        ],
      ),
      CategoryHierarchy(
        id: 'motor',
        name: 'Deportes de Motor',
        emoji: '🏁',
        priority: 2,
        discoveryQueries: ['motorsport', 'racing', 'race car'],
        subcategories: [
          CategoryHierarchy(
            id: 'f1',
            name: 'Fórmula 1',
            emoji: '🏎️',
            discoveryQueries: [
              'F1',
              'Formula 1',
              'Formula One',
              'Lewis Hamilton',
              'Max Verstappen',
              'Fernando Alonso',
              'Charles Leclerc',
              'Lando Norris',
            ],
          ),
          CategoryHierarchy(
            id: 'f2',
            name: 'Fórmula 2',
            emoji: '🏎️',
            discoveryQueries: ['F2', 'Formula 2', 'Formula 2 racing'],
          ),
          CategoryHierarchy(
            id: 'motogp',
            name: 'MotoGP',
            emoji: '🏍️',
            discoveryQueries: [
              'MotoGP',
              'Moto GP',
              'motorcycle racing',
              'Marc Márquez',
              'Jorge Lorenzo',
              'Valentino Rossi',
            ],
          ),
          CategoryHierarchy(
            id: 'moto2',
            name: 'Moto2',
            emoji: '🏍️',
            discoveryQueries: ['Moto2', 'Moto 2'],
          ),
          CategoryHierarchy(
            id: 'motocross',
            name: 'Motocross',
            emoji: '🏍️',
            discoveryQueries: ['motocross', 'dirt bike', 'cross racing'],
          ),
          CategoryHierarchy(
            id: 'nascar',
            name: 'NASCAR',
            emoji: '🏎️',
            discoveryQueries: ['NASCAR', 'stock car', 'american racing'],
          ),
          CategoryHierarchy(
            id: 'wrc',
            name: 'Rally / WRC',
            emoji: '🏎️',
            discoveryQueries: ['rally', 'WRC', 'World Rally Championship', 'rallycar'],
          ),
          CategoryHierarchy(
            id: 'wec',
            name: 'WEC / Le Mans',
            emoji: '🏎️',
            discoveryQueries: ['WEC', 'Le Mans', 'endurance racing', '24 hours'],
          ),
        ],
      ),
      CategoryHierarchy(
        id: 'basquetbol',
        name: 'Básquetbol',
        emoji: '🏀',
        priority: 3,
        discoveryQueries: [
          'basketball',
          'NBA',
          'Lebron James',
          'Michael Jordan',
          'Giannis Antetokounmpo',
          'Luka Doncic',
        ],
      ),
      CategoryHierarchy(
        id: 'tenis',
        name: 'Tenis',
        emoji: '🎾',
        priority: 4,
        discoveryQueries: ['tennis', 'Wimbledon', 'US Open', 'Djokovic', 'Federer'],
      ),
      CategoryHierarchy(
        id: 'americano',
        name: 'Fútbol Americano (NFL)',
        emoji: '🏈',
        priority: 5,
        discoveryQueries: ['NFL', 'American football', 'football', 'NFL quarterback'],
      ),
      CategoryHierarchy(
        id: 'beisbol',
        name: 'Béisbol (MLB)',
        emoji: '⚾',
        priority: 6,
        discoveryQueries: ['baseball', 'MLB', 'major league baseball'],
      ),
      CategoryHierarchy(
        id: 'hockey',
        name: 'Hockey sobre hielo (NHL)',
        emoji: '🏒',
        priority: 7,
        discoveryQueries: ['hockey', 'NHL', 'ice hockey'],
      ),
      CategoryHierarchy(
        id: 'rugby',
        name: 'Rugby',
        emoji: '🏉',
        priority: 8,
        discoveryQueries: ['rugby', 'rugby union', 'rugby league'],
      ),
      CategoryHierarchy(
        id: 'golf',
        name: 'Golf',
        emoji: '⛳',
        priority: 9,
        discoveryQueries: ['golf', 'PGA', 'master golf', 'golfer'],
      ),
      CategoryHierarchy(
        id: 'ciclismo',
        name: 'Ciclismo',
        emoji: '🚴',
        priority: 10,
        discoveryQueries: ['cycling', 'Tour de France', 'cyclist', 'bike racing'],
      ),
      CategoryHierarchy(
        id: 'atletismo',
        name: 'Atletismo',
        emoji: '🏃',
        priority: 11,
        discoveryQueries: ['athletics', 'track and field', 'running', 'olympics'],
      ),
      CategoryHierarchy(
        id: 'natacion',
        name: 'Natación',
        emoji: '🏊',
        priority: 12,
        discoveryQueries: ['swimming', 'swimmer', 'olympic swimming'],
      ),
      CategoryHierarchy(
        id: 'boxeo',
        name: 'Boxeo',
        emoji: '🥊',
        priority: 13,
        discoveryQueries: ['boxing', 'boxer', 'heavyweight', 'boxing championship'],
      ),
      CategoryHierarchy(
        id: 'mma',
        name: 'MMA / UFC',
        emoji: '🥋',
        priority: 14,
        discoveryQueries: [
          'MMA',
          'UFC',
          'mixed martial arts',
          'fighting',
          'Conor McGregor',
        ],
      ),
      CategoryHierarchy(
        id: 'voleibol',
        name: 'Voleibol',
        emoji: '🏐',
        priority: 15,
        discoveryQueries: ['volleyball', 'beach volleyball'],
      ),
      CategoryHierarchy(
        id: 'surf',
        name: 'Surf',
        emoji: '🏄',
        priority: 16,
        discoveryQueries: ['surfing', 'surfer', 'waves', 'beach surf'],
      ),
      CategoryHierarchy(
        id: 'skateboarding',
        name: 'Skateboarding',
        emoji: '🛹',
        priority: 17,
        discoveryQueries: ['skateboard', 'skateboarding', 'skater'],
      ),
      CategoryHierarchy(
        id: 'otros-deportes',
        name: 'Otros deportes',
        emoji: '🥇',
        priority: 99,
        discoveryQueries: ['sports', 'athlete', 'athletic', 'competition'],
      ),
    ],
  ),
  CategoryHierarchy(
    id: 'celebridades',
    name: 'Celebridades',
    emoji: '🌟',
    description: 'Actores, cantantes, personalidades públicas',
    priority: 30,
    discoveryQueries: ['celebrity', 'actor', 'actress', 'musician', 'portrait'],
  ),
  CategoryHierarchy(
    id: 'peliculas-series',
    name: 'Películas y series',
    emoji: '🎬',
    description: 'Cine, televisión y streaming',
    priority: 35,
    discoveryQueries: [
      'movie',
      'film',
      'cinema',
      'TV series',
      'netflix',
      'movie poster',
    ],
  ),
  CategoryHierarchy(
    id: 'anime',
    name: 'Anime',
    emoji: '🎌',
    description: 'Anime, manga y artes visuales japonesas',
    priority: 40,
    discoveryQueries: [
      'anime',
      'manga',
      'japanese animation',
      'anime girl',
      'anime boy',
    ],
  ),
  CategoryHierarchy(
    id: 'videojuegos',
    name: 'Videojuegos',
    emoji: '🎮',
    description: 'Juegos, esports y gaming',
    priority: 45,
    discoveryQueries: [
      'video games',
      'gaming',
      'game',
      'esports',
      'gaming wallpaper',
    ],
  ),
  CategoryHierarchy(
    id: 'ciencia-ficcion',
    name: 'Ciencia ficción',
    emoji: '🚀',
    description: 'Sci-fi, futurista y conceptual',
    priority: 50,
    discoveryQueries: [
      'sci-fi',
      'science fiction',
      'futuristic',
      'space travel',
      'sci-fi wallpaper',
    ],
  ),
  CategoryHierarchy(
    id: 'fantasia',
    name: 'Fantasía',
    emoji: '🐉',
    description: 'Fantasía, magia y mundos imaginarios',
    priority: 55,
    discoveryQueries: ['fantasy', 'dragon', 'magic', 'wizard', 'fantasy art'],
  ),
  CategoryHierarchy(
    id: 'tecnologia',
    name: 'Tecnología',
    emoji: '🤖',
    description: 'Tech, gadgets, IA y futuro',
    priority: 60,
    discoveryQueries: ['technology', 'tech', 'AI', 'robot', 'digital', 'coding'],
  ),
  CategoryHierarchy(
    id: 'tablets',
    name: 'Tablets',
    emoji: '💻',
    description: 'Formatos panorámicos para tablets',
    priority: 99,
    forcePortraitCrop: false,
    discoveryQueries: ['landscape', 'widescreen', 'panorama'],
  ),
];
